

export const ActionTypes={
    ADD_CART:"ADD_CART",
    DELETE_CART:"DELETE_CART",
    GET_NUMBER_CART:"GET_NUMBER_CART",
    INCREASE_QUANTITY:"INCREASE_QUANTITY",
    DECREASE_QUANTITY:"DECREASE_QUANTITY",
    FAVOURITE:"FAVOURITE",
    TOTAL_PRICE:"TOTAL PRICE"
}